language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf libpam0g-dev autotools-dev cgroup-lite
  - gem install rake
env:
  - MRUBY_VERSION=1.2.0
  - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=master
script:
  - rake
